one:
	mkdir -p ../check
	cp ../src/Regex.py ../check
	python3 ../check/Regex.py > output.txt
	grep "'Th', 'q', 'ck', 'br', 'wn', 'f', 'x', 'j', 'mps', 'v', 'r', 'th', 'l', 'zy', 'd', 'g.'" output.txt

two:
	mkdir -p ../check
	cp ../src/Regex.py ../check
	python3 ../check/Regex.py > output.txt
	grep "('http', 'example.com')" output.txt

three:
	mkdir -p ../check
	cp ../src/Regex.py ../check
	python3 ../check/Regex.py > output.txt
	grep "'/interactive', '/target/target', '/bleeding-edge', '/user-centric'" output.txt
